### PR TITLE
Remove init script.

### PR DESCRIPTION
**Pull request by runningcode**
Remove init script in favor of directly applying GE plugin.

### CODE REVIEW

**Comment by runningcode** [comment]
@ghale do we still need the init script for debugging tests?

**Comment by etiennestuder** [comment]
If we still need it for debugging, let's store it somewhere internally but not in this repo. It's confusing to have such an init script that instruments the build for GE.

**Comment by ghale** [comment]
Echo what Etienne said.  Let's just get rid of it.  We can always handle test debugging separately.

**Review by ghale — APPROVED** [review]
LGTM

**Pull request merged**
